### ISSUE TITLE
Possible bug in NetIPv4_GetAddrSrcHandler()

### ISSUE THREAD

**Issue by wes-jmagasrevy** [SiliconLabs/uC-TCP-IP#17]
`NetIPv4_GetAddrSrcHandler()` checks if the IP address contained in variable `'addr_remote'` resides in the same subnet as the IP address configured in the current interface. The problem is that `'addr_remote'` is in network order and hence that comparison will always fail. In other words, the **if** statement on line 2447 of _net_ipv4.c_ (V3.05.00) should be:

```
if ((NET_UTIL_NET_TO_HOST_32(addr_remote) & p_ip_addrs->AddrHostSubnetMask) == p_ip_addrs->AddrHostSubnetNet) {
}
```

**Comment by peschuster** [comment]
We are currently investigating a bug caused by the fix in #26 

The function header clearly states that addresses passed to this function must be in host order. See note 3:
`(3) IPv4 addresses MUST be in host-order.`

I think the conversion should be done in one of the callers, not here in this function.

**Comment by yasosa305** [comment]
Hi @peschuster. Can you share with us the nature of the bug and the call stack leading up to NetIPv4_GetAddrSrcHandler()? Thanks!

**Comment by peschuster** [comment]
The entry point from our application is `NetICMP_TxEchoReq` with an IP address as parameter that was returned from `NetASCII_Str_to_IPv4`.

**Comment by peschuster** [comment]
@yasosa305 were you able to look into this?
We reverted this change and have no issue with uC-HTTPs, uC-SNTPc, uC-TFTP, the above mentioned NetICMP_TxEchoReq and other TCP based servers.
