### ISSUE TITLE
NetBuf_Discard Out of Bound Write

### ISSUE THREAD

**Issue by mpanther** [SiliconLabs/uC-TCP-IP#2]
net_buf.c line 3113.

No check on if_nbr so if out of range (ie 0xFF), the err ctr will increment at memory address out of bounds.
Probably replace with:

    if(if_nbr < NET_IF_NBR_IF_TOT)
    {
      NET_CTR_ERR_INC(Net_ErrCtrs.IFs.IF[if_nbr].BufLostCtr);
    }

**Comment by yasosa305** [comment]
Hi Mitch,
     Thanks for bringing this up to our attention. After reviewing your submission, we agree that there should be a final check here because the NetBuf_FreeHandler() -> NetBuf_Discard() path only checks for that argument when the NET_ERR_CFG_ARG_CHK_DBG_EN feature is turned on. All other paths that lead to this function make sure this argument is checked regardless of NET_ERR_CFG_ARG_CHK_DBG_EN.
