### ISSUE TITLE
axi-ethernet files are not complete 

### ISSUE THREAD

**Issue by SajedeNick1999** [SiliconLabs/uC-TCP-IP#34]
Hi 
I want to use axi-ethernet.
Which `NetDev_API_<controller>`  should I use in `NetIF_Add` function?
Note : file "ucos_tcpip_init" for this purpose uses `NetDev_API_XIL_ETHER` from "Dev/Ether/XIL_ETHER/net_dev_xil_ether.h" but net_dev_xil_ether.h does not exist in repository

regards,

**Comment by forg0ne** [comment]
Hello,
Unfortunately, support for axi-ethernet is not available.
The references to that driver may have been mistakenly added at some point in the past when a driver was in development, but the open-sourced version of the uC stacks don't appear to support it.
I recommend use of the axi-ethernet-lite instead.
