### ISSUE TITLE
'data_avail' may be used uninitialized in NetTCP_RxPktConnHandlerFinWait2()

### ISSUE THREAD

**Issue by tgAtSercel** [SiliconLabs/uC-TCP-IP#9]
In file net_tcp.c, function "NetTCP_RxPktConnHandlerFinWait2()" the local variable "data_avail" may be used unitialized by the return statement,

Best Regards,

Thomas GIRARD

**Comment by wes-jmagasrevy** [comment]
This has now been fixed. Thanks for the input @tgAtSercel
